### ISSUE TITLE
Duplicate module name: Sample

### ISSUE THREAD

**Issue by masaok** [expo/expo-pixi#84]
When running the `filter-image` example, I get this error:

```
(node:3942) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: Sample
  Paths: <HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/expo-pixi/examples/signature/node_modules/react-native/Libraries/Sample/package.json collides with <HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/expo-pixi/node_modules/react-native/Libraries/Sample/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at setModule (<HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/jest-haste-map/build/index.js:462:17)
    at workerReply (<HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/jest-haste-map/build/index.js:512:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:3942) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When lined up next to each other:

```
<HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/expo-pixi/examples/signature/node_modules/react-native/Libraries/Sample/package.json
<HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/expo-pixi/node_modules/react-native/Libraries/Sample/package.json
```

...the `signature` example module is conflicting with the `filter-image` module.

**Comment by masaok** [comment]
I found a workaround here: https://github.com/99xt/first-born/issues/4#issuecomment-478923842

Simply delete the deeper node_modules directory.

In the example above, delete this one:
```
<HOME>/github/expo/expo-pixi/examples/filter-image/node_modules/expo-pixi/examples/signature/node_modules
```
You may have to do this multiple times with various conflicting directories.
